name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: eufopla
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=blue
            dist/github-contribution-grid-snake-dark.svg?palette=blue

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "generate snake"
          file_pattern: dist/*.svg
